#!/usr/bin/env python3

# Standard library imports:
import sys
from pathlib import Path
import datetime
import argparse

# Custom imports:
from biolib.files.pdbcif import CifFileCollection


def createParser():
    parser = argparse.ArgumentParser(prog='extract_foldseek_clusters_from_cif_collection',
                                     description='Given a cif collection and a foldseek cluster result (adjacency matrix as .tsv file), create a new directory containing only the representative chains as new cif files. Please beware that most of the data besides the _atom_site and _entry.id will get lost. Hetero atoms are filtered by default.',
                                     epilog='Created by mimitair.'
                                     )

    parser.add_argument('path_to_cif_collection', action='store', type=Path, help='Path to the cif collection')
    parser.add_argument('path_to_foldseek_cluster', action='store', type=Path, help='Path to the foldseek adjacency matirx as .tsv file')
    parser.add_argument('out_dir', action='store', type=Path, help='Path to the desired output directory. Will be created if non-existent.')

    return parser


def main():
    # Parse arguments:
    args = createParser().parse_args()

    mycoll = CifFileCollection(args.path_to_cif_collection)
    print(f'Amount of cif files in collection: {mycoll.size}')
    print('Extracting clusters...')
    mycoll.extractFoldseekClusters(args.path_to_foldseek_cluster, args.out_dir)
    print(f'Amount of cif files (cluster representatives) in new collection: {CifFileCollection(args.out_dir).size}')

    
if __name__ == "__main__":

    start = datetime.datetime.now()
    print(f"--- SCRIPT: {__file__} ---")
    print(f"--- COMMAND: {' '.join(sys.argv)} ---")
    print(f"--- START: {start} ---")

    main()
    
    end = datetime.datetime.now()
    print(f"--- END: {end} ---")
    print(f"--- TIME ELAPSED: {end - start} ---")
