#!/usr/bin/env python3

"""

Usage:
"""

# Standard library imports:
import sys
from pathlib import Path
import datetime
from biolib.files.foldseek_out import EasyClustOut

def main():
    in_dir: str = sys.argv[1]
    min_length: int = int(sys.argv[2])
    max_length: int = int(sys.argv[3])
    out_dir: str = sys.argv[4]
    
    clust_out: EasyClustOut = EasyClustOut(in_dir)

    clust_out.filterRepresentativesByLength(min_length, max_length, out_dir=out_dir)

if __name__ == "__main__":

    print(f"--- SCRIPT: {__file__} ---")
    print(f"--- COMMAND: {' '.join(sys.argv)} ---")
    print(f"--- START: {datetime.datetime.now()} ---")

    main()
    
    print(f"--- END: {datetime.datetime.now()} ---")
