#! /usr/bin/env python3

import sys
from pathlib import Path
from biolib.files.pdbcif import CifFileCollection
import datetime

def main():
    print(f"--- SCRIPT: {__file__} ---")
    print(f"--- START: {datetime.datetime.now()} ---")
    
    in_dir: Path = Path(sys.argv[1])
    out_dir: Path = Path(sys.argv[2])
    
    # Convert to cif file collection object:
    mycoll = CifFileCollection(in_dir)
    print(f"Found {mycoll.size} .cif files in {mycoll.name}")
    
    # Filter the mutants:
    mutants = mycoll.filterMutants(out_dir)
    print(f"Found {len(mutants)} mutants ({(len(mutants)/mycoll.size)*100:,.2f}% of collection)")
    
    print(f"--- END: {datetime.datetime.now()} ---")
    
if __name__ == "__main__":
    main()
