#! /usr/bin/env python3

"""
Script to find three neigbouring residues based on distance thresholds in a cif file.
"""
from pathlib import Path
from biolib.files.pdbcif import CifFile
import sys
import itertools
PAIR1: tuple = ('SER@OG', 'HIS@NE2')
PAIR2: tuple = ('HIS@ND1', 'ASP@OD2')
PAIR3: tuple = ('ASP@OD2', 'SER@OG')
MAX_DIST_PAIR1: float = 3
MAX_DIST_PAIR2: float = 3
MAX_DIST_PAIR3: float = 7.2

def main():
    # Read the arguments:
    in_file: Path = Path(sys.argv[1])
    #out_file: Path = Path(sys.argv[2])

    # Convert input file to Cif object:
    mycif: CifFile = CifFile(in_file)

    result = CifFile.findTriads(mycif.toBiotiteAtomArray(),PAIR1, PAIR2, PAIR3, MAX_DIST_PAIR1, MAX_DIST_PAIR2, MAX_DIST_PAIR3)
    
    for a in result:
        print((a.res_name, a.res_id, a.chain_id))

    return 0
    
if __name__ == "__main__":
    main()
