#!/usr/bin/env python3

import sys
from pathlib import Path
from biolib.files.fpocket_out import FpocketOutCollection

def main():
    in_dir: str = sys.argv[1]
    out_file: str = sys.argv[2]

    mycoll = FpocketOutCollection(in_dir)

    mycoll.pocketInfoToDf(out_file)
    
    return 0

if __name__ == "__main__":
    main()
