#!/usr/bin/env python3

import sys
from pathlib import Path
import datetime
from biolib.files.pdbcif import CifFileCollection

def main():
    in_dir: Path = Path(sys.argv[1]).resolve()
    enzymm_out_path: Path = Path(sys.argv[2]).resolve()
    fpocket_out_coll: Path = Path(sys.argv[3]).resolve()
    out_file: Path = Path(sys.argv[4]).resolve()

    mycoll = CifFileCollection(in_dir)

    df = mycoll.getCatalyticSitePockets(enzymm_out_path, fpocket_out_coll)

    df.to_csv(out_file, index_label='query_id')
    
if __name__ == "__main__":

    print(f"--- SCRIPT: {__file__} ---")
    print(f"--- COMMAND: {' '.join(sys.argv)} ---")
    print(f"--- START: {datetime.datetime.now()} ---")

    main()
    
    print(f"--- END: {datetime.datetime.now()} ---")
