#!/usr/bin/env python3

import sys
from pathlib import Path
from biolib.files.fasta import FastaFile
import numpy as np

def main():
    in_file: Path = Path(sys.argv[1])
    
    myfasta: FastaFile = FastaFile(in_file)

    lengths: np.ndarray = np.array(myfasta.getLengths())
    
    print(f"Mean length: {np.mean(lengths)}")
    print(f"Median lenght: {np.median(lengths)}")
    print(f"Std: {np.std(lengths)}")
    print(f"Min length: {np.min(lengths)}")
    print(f"Max length: {np.max(lengths)}")
    
    # Plot lengths:
    myfasta.plotLengthHistogram("Length", "Count", "Sequence length histogram")
    myfasta.plotLengthBox()
    
    return 0


if __name__ == "__main__":
    main()
    
