#! /usr/bin/env python3

"""
Usage: p3 plot_ramachandran <input_cif_file> <output_plot_file>
Code source: Patrick Kunzmann
License: BSD 3 clause
https://www.biotite-python.org/latest/examples/gallery/structure/protein/ramachandran.html#sphx-glr-examples-gallery-structure-protein-ramachandran-py
Adapted by mimitair
"""

# Imports:
import matplotlib.pyplot as plt
import numpy as np
import sys
from pathlib import Path
import biotite.structure as struc
import biotite.structure.io as strucio
import biotite.structure.io.pdbx as pdbxio

def main():
    # Specifiy the cif file as the first cli argument:
    in_file: Path = Path(sys.argv[1])
    
    # cast in_file to CIFFile object and extract the pdb id:
    my_cif: CIFFile = pdbxio.CIFFile.read(in_file)
    my_cif_pdb_id: str = my_cif.block['entry']['id'].as_item()

    # Load as atom array
    atom_array = strucio.load_structure(in_file)
    
    # Extract first peptide chain
    peptide = atom_array[struc.filter_amino_acids(atom_array)]
    chain = peptide[peptide.chain_id == "A"]
    
    # Calculate backbone dihedral angles
    # from one of the two identical chains in the asymmetric unit
    phi, psi, omega = struc.dihedral_backbone(chain)
    phi = np.rad2deg(phi)
    psi = np.rad2deg(psi)
    # Remove invalid values (NaN) at first and last position
    phi = phi[1:-1]
    psi = psi[1:-1]

    # Plot density
    figure = plt.figure()
    ax = figure.add_subplot(111)
    h, xed, yed, image = ax.hist2d(phi, psi, bins=(200, 200), cmap="RdYlGn_r", cmin=1)
    cbar = figure.colorbar(image, orientation="vertical")
    cbar.set_label("Count")
    ax.set_aspect("equal")
    ax.set_xlim(-180, 175)
    ax.set_ylim(-180, 175)
    ax.set_xlabel(r"$\phi$")
    ax.set_ylabel(r"$\psi$")
    ax.set_title(f"Ramachandran plot of {my_cif_pdb_id}")
    figure.tight_layout()
    plt.show()

if __name__ == "__main__":
    main()
