#!/usr/bin/env python3

"""
Create new directory with symlinks to cif files in the given collection, devoid of the files where the ID matches those of the given ID list (.txt file).
Usage: remove_ids_in_cif_collection <path_to_cif_coll> <path_to_id_list> <out_dir>
"""
import sys
from pathlib import Path
import datetime
from biolib.files.pdbcif import CifFileCollection

def main():

    path_to_cif_coll: str = sys.argv[1]
    path_to_ids: str = sys.argv[2]
    out_dir: str = sys.argv[3]

    # Convert to CifFileCollection object:
    mycoll: CifFileCollection = CifFileCollection(path_to_cif_coll)
    print(f"Size of cif collection: {mycoll.size}")
       
    # Call the appropriate function:
    removed: list = mycoll.removeIDs(path_to_ids=path_to_ids, out_dir=out_dir)
    print(f"Files removed based on IDs: {len(removed)}")

if __name__ == "__main__":

    print(f"--- SCRIPT: {__file__} ---")
    print(f"--- COMMAND: {' '.join(sys.argv)} ---")
    print(f"--- START: {datetime.datetime.now()} ---")

    main()
    
    print(f"--- END: {datetime.datetime.now()} ---")
