#!/usr/bin/env python3

from biolib.files.pdbcif import CifFileCollection
import sys
from pathlib import Path
import datetime

def main():
    
    in_dir: Path = Path(sys.argv[1])
    in_enzymm: Path = Path(sys.argv[2])
    out_dir: Path = Path(sys.argv[3])
        
    mycoll = CifFileCollection(in_dir)
    
    mycoll.runFpocketWithEnzymmChains(in_enzymm, out_dir)

if __name__ == "__main__":

    print(f"--- SCRIPT: {__file__} ---")
    print(f"--- COMMAND: {' '.join(sys.argv)} ---")
    print(f"--- START: {datetime.datetime.now()} ---")

    main()
    
    print(f"--- END: {datetime.datetime.now()} ---")


